name: build
on:
  workflow_dispatch:
    inputs:
      BOARD:
        required: true
        type: string
        default: "rpi4"
      PLATFORM:
        required: true
        type: choice
        default: "v2-hdmiusb"
        options:
          - v2-hdmiusb
          - v2-hdmi
      ARCH:
        required: true
        type: choice
        default: "arm"
        options:
          - arm
          - aarch64
      SUFFIX:
        required: false
        type: string
        default:
      OLED:
        required: false
        type: string
        default:
      FAN:
        required: false
        type: string
        default:


jobs:
  os:
    runs-on: ubuntu-latest
    env:
      BOARD: "${{inputs.BOARD}}"
      PLATFORM: "${{inputs.PLATFORM}}"
      ARCH: "${{inputs.ARCH}}"
      SUFFIX: "${{inputs.SUFFIX}}"
      OLED: "${{inputs.OLED}}"
      FAN: "${{inputs.FAN}}"
      TERM: xterm
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Creating config.mk
        run: |
          echo "BOARD=$BOARD" > config.mk
          echo "PLATFORM=$PLATFORM" >> config.mk
          echo "ARCH=$ARCH" >> config.mk
          echo "DEPLOY_USER=data" >> config.mk
          echo "SUFFIX=$SUFFIX" >> config.mk
          echo "OLED=$OLED" >> config.mk
          echo "FAN=$FAN" >> config.mk

      - name: Building OS
        run: make os NC=1

      - name: Making image
        run: make image IMAGE_XZ=1

      - name: Archive image
        uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.BOARD }}-Arch-Linux-PiKVM-${{ inputs.ARCH }}
          path: ${{ github.workspace }}/images/${{ inputs.PLATFORM }}-${{ inputs.BOARD }}/${{ inputs.ARCH }}/${{ inputs.PLATFORM }}-${{ inputs.BOARD }}-${{ inputs.ARCH }}-latest.img.xz
